name: Build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows x64 Configuration
          - os: windows-2025
            sdk_version: 10.0.26100.0
            msvc_compiler_tuple: amd64
            msbuild_platform: x64
            cmake_build_tuple: x64 x64
            openssl_build_tuple: x64 VC-WIN64A-masm
            ffmpeg_build_tuple: x64
            libplacebo_build_tuple: x64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 1

      - name: Setup Environment (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          choco install -y nasm jom
          pip install meson ninja

      - name: Setup MSVC (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_compiler_tuple }}
          sdk: ${{ matrix.sdk_version }}

      - name: Setup MSYS2 (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          update: true
          install: >-
            make
            git

      - name: Install Vulkan SDK (Windows)
        if: runner.os == 'Windows'
        uses: cgutman/install-vulkan-sdk@warm_qt
        with:
          version: 1.4.321.1
          cache: true

      - name: Setup Build Directory
        shell: bash
        run: |
          mkdir build
          mkdir build/dav1d
          mkdir build/FFmpeg

      - name: Build dav1d (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        working-directory: build/dav1d
        run: |
          ..\\..\\build-dav1d.bat ${{ matrix.ffmpeg_build_tuple }}

      - name: Build FFmpeg (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        working-directory: build
        run: |
          ../build-ffmpeg-windows.sh ${{ matrix.ffmpeg_build_tuple }}

      - name: Archive Build Artifacts (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          archive.bat ${{ matrix.msbuild_platform }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.msbuild_platform || 'universal' }}
          path: |
            windows-*.zip
            macos.zip
          if-no-files-found: error